-- ============================================================
-- SCHEMA SUPABASE - IRAI MANUTENZIONE
-- UNI 11224:2019/2021 CONFORME
-- ============================================================

-- ENABLE EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- TABELLE
-- ============================================================

CREATE TABLE clienti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ragione_sociale VARCHAR(255) NOT NULL,
    partita_iva VARCHAR(11) UNIQUE,
    codice_fiscale VARCHAR(16),
    indirizzo VARCHAR(255),
    cap VARCHAR(5),
    città VARCHAR(100),
    provincia VARCHAR(2),
    telefono VARCHAR(50),
    email VARCHAR(100),
    pec VARCHAR(100),
    rappresentante_legale VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    active BOOLEAN DEFAULT TRUE
);

CREATE TABLE sedi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clienti(id) ON DELETE CASCADE,
    nome_sede VARCHAR(255) NOT NULL,
    indirizzo VARCHAR(255),
    cap VARCHAR(5),
    città VARCHAR(100),
    provincia VARCHAR(2),
    attività VARCHAR(255),
    attività_ateco VARCHAR(10),
    superficie_mq INTEGER,
    altezza_metri DECIMAL(5,2),
    livello_rischio VARCHAR(20) CHECK (livello_rischio IN ('basso', 'medio', 'elevato', 'molto elevato')),
    piano VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    active BOOLEAN DEFAULT TRUE
);

CREATE TABLE centrali (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sede_id BIGINT REFERENCES sedi(id) ON DELETE CASCADE,
    marca VARCHAR(100) NOT NULL,
    modello VARCHAR(100),
    numero_serie VARCHAR(100) UNIQUE,
    anno_installazione INTEGER,
    anno_revisione_generale INTEGER,
    protocollo_indirizzo VARCHAR(50),
    tcp_port INTEGER DEFAULT 502,
    centrale_tipologia VARCHAR(50) CHECK (centrale_tipologia IN ('convenzionale', 'indirizzata', 'analogica', 'mista')),
    zona_centrale VARCHAR(100),
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    active BOOLEAN DEFAULT TRUE
);

CREATE TABLE dispositivi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    centrale_id BIGINT REFERENCES centrali(id) ON DELETE CASCADE,
    dispositivo_tipo VARCHAR(50) NOT NULL CHECK (
        dispositivo_tipo IN (
            'rilevatore_fumo', 'rilevatore_calore', 'rilevatore_fumo_calore',
            'rilevatore_lineare', 'rilevatore_gas', 'rilevatore_raggi_infrarossi',
            'pulsante_allarme', 'sirena', 'lampeggiante', 'modulo_supervisione',
            'elettromagnete', 'rilevatore_unico', 'porta_rete', 'unità_centrale'
        )
    ),
    indirizzo_centrale VARCHAR(20),
    zona VARCHAR(100),
    posizione VARCHAR(255),
    piano VARCHAR(50),
    ambiente VARCHAR(100),
    marca VARCHAR(100),
    modello VARCHAR(100),
    numero_serie VARCHAR(100) UNIQUE,
    data_installazione DATE,
    data_ultima_manutenzione DATE,
    stato VARCHAR(20) DEFAULT 'attivo' CHECK (stato IN ('attivo', 'disattivato', 'guasto', 'sostituito')),
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    active BOOLEAN DEFAULT TRUE
);

CREATE TABLE piani_manutenzione (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    centrale_id BIGINT REFERENCES centrali(id) ON DELETE CASCADE,
    protocollo_tipo VARCHAR(50) NOT NULL CHECK (
        protocollo_tipo IN ('sorveglianza', 'controllo_periodico', 'revisione', 'verifica_generale')
    ),
    frequenza_mesi INTEGER NOT NULL CHECK (frequenza_mesi IN (6, 12, 24, 60, 120)),
    data_prevista DATE NOT NULL,
    data_effettiva DATE,
    tecnico_id BIGINT,
    stato VARCHAR(20) DEFAULT 'pendente' CHECK (stato IN ('pendente', 'in_corso', 'completato', 'annullato')),
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE verifiche_punto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    piano_id BIGINT REFERENCES piani_manutenzione(id) ON DELETE CASCADE,
    dispositivo_id BIGINT REFERENCES dispositivi(id) ON DELETE SET NULL,
    punto_norma VARCHAR(50) NOT NULL,
    tipologia_prova VARCHAR(50) NOT NULL CHECK (
        tipologia_prova IN ('prova_funzionalità', 'prova_efficacia', 'prova_complessiva')
    ),
    esito BOOLEAN,
    valore_rilevato VARCHAR(50),
    soglia_conformità VARCHAR(50),
    foto_prima BYTEA,
    foto_dopo BYTEA,
    ora_inizio TIMESTAMP WITH TIME ZONE,
    ora_fine TIMESTAMP WITH TIME ZONE,
    tecnico VARCHAR(255),
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    UNIQUE(piano_id, dispositivo_id, punto_norma)
);

CREATE TABLE registro_antincendio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervento_id BIGINT,
    sede_id BIGINT REFERENCES sedi(id) ON DELETE SET NULL,
    centrale_id BIGINT REFERENCES centrali(id) ON DELETE SET NULL,
    dispositivo_id BIGINT REFERENCES dispositivi(id) ON DELETE SET NULL,
    data_intervento DATE NOT NULL,
    ora_intervento TIME NOT NULL,
    attività_svolta TEXT NOT NULL,
    esito_intervento VARCHAR(20) CHECK (esito_intervento IN ('conformità', 'non_conformità', 'guasto', 'sostituzione')),
    tecnico VARCHAR(255) NOT NULL,
    firma_tecnico VARCHAR(255),
    data_verbale DATE,
    numero_verbale VARCHAR(50) UNIQUE,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE non_conformita (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    verifica_id BIGINT REFERENCES verifiche_punto(id) ON DELETE SET NULL,
    dispositivo_id BIGINT REFERENCES dispositivi(id) ON DELETE SET NULL,
    centrale_id BIGINT REFERENCES centrali(id) ON DELETE SET NULL,
    nc_tipo VARCHAR(50) NOT NULL CHECK (
        nc_tipo IN ('anomalia', 'guasto', 'difetto', 'mancanza_ricambio', 'ritardo_intervento')
    ),
    gravità VARCHAR(20) CHECK (gravità IN ('bassa', 'media', 'alta', 'critica')),
    descrizione TEXT NOT NULL,
    causa_probabile TEXT,
    azione_correttiva TEXT,
    pezzi_ricambio TEXT,
    stato VARCHAR(20) DEFAULT 'aperta' CHECK (stato IN ('aperta', 'in_gestione', 'risolta', 'chiusa')),
    data_apertura DATE DEFAULT CURRENT_DATE,
    data_chiusura DATE,
    foto_guasto BYTEA,
    costo DECIMAL(10,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE profili (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email VARCHAR(255) NOT NULL,
    nome VARCHAR(100),
    cognome VARCHAR(100),
    telefono VARCHAR(50),
    ruolo VARCHAR(20) DEFAULT 'tecnico' CHECK (ruolo IN ('admin', 'tecnico', 'lettura')),
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tecnici (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profilo_id UUID REFERENCES profili(id) ON DELETE SET NULL,
    nome VARCHAR(100) NOT NULL,
    cognome VARCHAR(100) NOT NULL,
    codice_fiscale VARCHAR(16) UNIQUE,
    email VARCHAR(100),
    telefono VARCHAR(50),
    qualifica VARCHAR(100),
    certificationi TEXT[],
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- Trigger automatico per creare profilo alla registrazione
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profili (id, email, nome, cognome, ruolo)
    VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data->>'nome', NEW.raw_user_meta_data->>'cognome', 'tecnico');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION handle_new_user();

CREATE TABLE verbali (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    piano_id BIGINT REFERENCES piani_manutenzione(id) ON DELETE SET NULL,
    registro_id BIGINT REFERENCES registro_antincendio(id) ON DELETE SET NULL,
    tecnico_id BIGINT REFERENCES tecnici(id) ON DELETE SET NULL,
    centrale_id BIGINT REFERENCES centrali(id) ON DELETE SET NULL,
    numero_verbale VARCHAR(50) UNIQUE NOT NULL,
    data_verifica DATE NOT NULL,
    protocollo_tipo VARCHAR(50),
    totali_punti INTEGER,
    punti_conformi INTEGER,
    perc_conformità DECIMAL(5,2),
    pdf_path VARCHAR(500),
    firma_tecnico BYTEA,
    data_firma TIMESTAMP WITH TIME ZONE,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- ============================================================
-- VIEWS
-- ============================================================

CREATE OR REPLACE VIEW scadenze_imminenti AS
SELECT
    pm.id,
    pm.centrale_id,
    pm.data_prevista,
    pm.stato,
    pm.protocollo_tipo,
    pm.data_prevista - CURRENT_DATE AS giorni_rimanenti
FROM piani_manutenzione pm
WHERE pm.stato IN ('pendente', 'in_corso');

CREATE OR REPLACE VIEW copertura_ciclo AS
SELECT
    c.id,
    c.marca,
    c.modello,
    COUNT(d.id) AS totale_dispositivi
FROM centrali c
LEFT JOIN dispositivi d ON d.centrale_id = c.id
GROUP BY c.id, c.marca, c.modello;

-- ============================================================
-- INDEX
-- ============================================================

CREATE INDEX idx_dispositivi_centrale ON dispositivi(centrale_id);
CREATE INDEX idx_dispositivi_stato ON dispositivi(stato);
CREATE INDEX idx_piani_centrale ON piani_manutenzione(centrale_id, data_prevista);
CREATE INDEX idx_verifiche_piano ON verifiche_punto(piano_id, dispositivo_id);
CREATE INDEX idx_nc_stato ON non_conformita(stato);
CREATE INDEX idx_registro_data ON registro_antincendio(data_intervento);

-- ============================================================
-- ROW LEVEL SECURITY (SUPABASE)
-- ============================================================

ALTER TABLE clienti ENABLE ROW LEVEL SECURITY;
ALTER TABLE sedi ENABLE ROW LEVEL SECURITY;
ALTER TABLE centrali ENABLE ROW LEVEL SECURITY;
ALTER TABLE dispositivi ENABLE ROW LEVEL SECURITY;
ALTER TABLE piani_manutenzione ENABLE ROW LEVEL SECURITY;
ALTER TABLE verifiche_punto ENABLE ROW LEVEL SECURITY;
ALTER TABLE non_conformita ENABLE ROW LEVEL SECURITY;
ALTER TABLE registro_antincendio ENABLE ROW LEVEL SECURITY;
ALTER TABLE verbali ENABLE ROW LEVEL SECURITY;
ALTER TABLE tecnici ENABLE ROW LEVEL SECURITY;

-- Policy per allow all in servizio (modifica per produzione)
CREATE POLICY "Allow all for clienti" ON clienti FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for sedi" ON sedi FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for centrali" ON centrali FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for dispositivi" ON dispositivi FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for piani" ON piani_manutenzione FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for verifiche" ON verifiche_punto FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for nc" ON non_conformita FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for registro" ON registro_antincendio FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for verbali" ON verbali FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for tecnici" ON tecnici FOR ALL USING (true) WITH CHECK (true);

-- Profili: solo proprietario può leggere/scrivere
ALTER TABLE profili ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Profili ownership" ON profili FOR ALL USING (auth.uid() = id) WITH CHECK (auth.uid() = id);